# Generated by Django 5.0.6 on 2024-06-17 06:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomManager',
        ),
        migrations.AlterModelManagers(
            name='books',
            managers=[
                ('new_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
